[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GenOT"
authors = [{name = "Rui Wang", email = "wangrui66677@gmail.com"}]
dynamic = ["version", "description"]
